server:
  port: 8080

spring:
  main:
    banner-mode: "off"

logging:
  pattern:
    console: "%d{yyyy-MM-dd-HH:mm:ss.SSS} %-5level [%X{traceId:-},%X{spanId:-}] [%thread] %logger - %msg%n%xEx"
  level:
    root: WARN
    cherry: TRACE
